### ISSUE TITLE
Is it possible to get a Python 3.10 version uploaded to PyPi?

### ISSUE THREAD

**Issue by eldritch-elbow** [SelfExplainML/Aletheia#9]
I'm currently attempting to use Aletheia in Google Colab which defaults to Python 3.10, and the aletheia-dnn library isn't resolved by pip.

I was wondering if it would be possible to arrange for a 3.10 compatible version to be made available?

As a workaround I'm attempting to downgrade the version of Python, but this is a bit of a faff and I'd prefer to avoid this if possible.

Thanks.

**Comment by ZebinYang** [comment]
Hi @j-siddle, The new version has been uploaded to Pypi. Now you can run the example notebooks in this repo on Colab.

**Comment by eldritch-elbow** [comment]
Awesome, thank you - I can confirm that the library is now available for installation using pip within Google Colab with python 3.10.
